baseURL = "https://michaleczky.github.io/drfoldvarszki-hu/"
languageCode = "hu-hu"
title = "Dr. Földvárszki Szimonetta Ügyvédi Iroda"
theme = "ananke"
sectionPagesMenu = "main"
publishDir = "docs"

DefaultContentLanguage = "hu"
MetaDataFormat = "toml"
Paginate = 3

[params]
    featured_image = "images/my-hero-image.jpg"