baseURL = "http://example.org/"
languageCode = "hu-hu"
title = "Dr. Földvárszki Szimonetta Ügyvédi Iroda"
theme = "ananke"
sectionPagesMenu = "main"
publishDir = "docs"

DefaultContentLanguage = "hu"
MetaDataFormat = "toml"
Paginate = 3
